CREATE TABLE `m_bank` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`bank` VARCHAR(500) NULL DEFAULT NULL,
	`ifsc` VARCHAR(500) NOT NULL,
	`micr_code` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(500) NULL DEFAULT NULL,
	`address` VARCHAR(500) NULL DEFAULT NULL,
	`contact` VARCHAR(50) NULL DEFAULT NULL,
	`city` VARCHAR(250) NULL DEFAULT NULL,
	`district` VARCHAR(250) NULL DEFAULT NULL,
	`state` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `ifsc` (`ifsc`)
)